title: Forumly
email: nathan@tryforumly.com
description: >- # this means to ignore newlines until "baseurl:"
  Native and bespoke iOS and Android apps for XenForo communties
baseurl: "/main-site" # the subpath of your site
url: "https://www.tryforumly.com" # the base hostname & protocol for your site

# build settings
markdown: kramdown
